# Generated by Django 5.1.5 on 2025-03-17 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_description', models.TextField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Better', 'Better'), ('Best', 'Best')], default='Good', max_length=10)),
                ('category', models.CharField(choices=[('Class 4-8', 'Class 4 8'), ('Class 9-12', 'Class 9 12'), ('Reference Book', 'Reference Book'), ('Children Book', 'Children Book'), ('Competition Book', 'Competition Book'), ('Other', 'Other')], default='Other', max_length=20)),
                ('subject', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='Other', max_length=20)),
                ('competitive_exam', models.CharField(choices=[('NEET', 'Neet'), ('JEE', 'Jee'), ('AIIMS', 'Aiims'), ('UPSC', 'Upsc'), ('SSC', 'Ssc'), ('GATE', 'Gate'), ('CAT', 'Cat'), ('Other', 'Other')], default='Other', max_length=20)),
                ('boards', models.CharField(choices=[('CBSE', 'Cbse'), ('ICSE', 'Icse'), ('ISC', 'Isc'), ('Other', 'Other')], default='Other', max_length=20)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='Other', max_length=20)),
                ('book_images', models.ImageField(blank=True, null=True, upload_to='book_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
