# Generated by Django 5.1.5 on 2025-03-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadbook',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('Political Science', 'Political Science'), ('Economics', 'Economics'), ('Civics', 'Civics'), ('Business Studies', 'Business Studies'), ('Sanskrit', 'Sanskriti'), ('Physical Education', 'Physical Education'), ('Computer Science', 'Computer Science'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
