# Generated by Django 5.1.5 on 2025-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_book', '0003_alter_uploadbook_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbook',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbook',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadbook',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadbook',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Sold', 'Sold')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadbook',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
