# Generated by Django 5.1.5 on 2025-01-25 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=50)),
                ('book_quantity', models.PositiveIntegerField()),
                ('book_expected_price', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('bad', 'Bad'), ('average', 'Average'), ('good', 'Good')], default='good', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sell_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sell_detail.selldetail')),
            ],
        ),
    ]
