# Generated by Django 5.1.5 on 2025-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_detail', '0002_selldetail_book_ai_price_selldetail_book_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldetail',
            name='sale_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selldetail',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
