# Generated by Django 5.1.5 on 2025-03-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_detail', '0004_sellorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selldetail',
            name='book_expected_price',
        ),
        migrations.AddField(
            model_name='selldetail',
            name='boards',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('UP', 'UP')], default='CBSE', max_length=10),
        ),
        migrations.AddField(
            model_name='selldetail',
            name='category',
            field=models.CharField(choices=[('class_4_8', 'Class 4-8'), ('class_9_12', 'Class 9-12'), ('reference', 'Reference'), ('competitive', 'Competitive'), ('childrens_book', "Children's Book")], default='reference', max_length=20),
        ),
        migrations.AddField(
            model_name='selldetail',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=10),
        ),
        migrations.AddField(
            model_name='selldetail',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('English', 'English'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('Political Science', 'Political Science'), ('Economics', 'Economics'), ('Civics', 'Civics'), ('Hindi', 'Hindi'), ('Business Study', 'Business Study'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='selldetail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='selldetail',
            name='condition',
            field=models.CharField(choices=[('best', 'Best'), ('better', 'Better'), ('good', 'Good')], default='good', max_length=10),
        ),
    ]
