# Generated by Django 5.1.5 on 2025-03-17 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_region', models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Argentina', 'Argentina'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Bangladesh', 'Bangladesh'), ('Belgium', 'Belgium'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('China', 'China'), ('Denmark', 'Denmark'), ('Egypt', 'Egypt'), ('France', 'France'), ('Germany', 'Germany'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Mexico', 'Mexico'), ('Netherlands', 'Netherlands'), ('Pakistan', 'Pakistan'), ('Russia', 'Russia'), ('Saudi Arabia', 'Saudi Arabia'), ('Singapore', 'Singapore'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Turkey', 'Turkey'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Other', 'Other')], default='India', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('flat_building_apartment', models.CharField(max_length=255)),
                ('area_street_village', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('default_address', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
